Repository woocommerce/woocommerce-square, pull requests merged in 2024-09, with the labels that each got.

#204 Release/4.8.0
  changelog.txt
  includes/Admin/Product_Editor_Compatibility.php
  package-lock.json
  package.json
  readme.txt
  tests/e2e/config/env-post-setup.sh
  tests/e2e/specs/d6.woo-sor.spec-with-inventory-new-editor.spec.js
  tests/e2e/specs/f1.pre-orders.spec.js
  tests/e2e/utils/helper.js
  woocommerce-square.php
Labels: status: e2e tests passing

#198 fix/30: Prevent Gift Card image from being forced upon a site
  includes/Admin.php
  includes/Admin/Rest/WC_REST_Square_Gift_Cards_Settings_Controller.php
  includes/Gateway/Gift_Card.php
  includes/Handlers/Products.php
  src/new-user-experience/onboarding/data/reducers.js
  src/new-user-experience/onboarding/steps/gift-card/index.js
  src/new-user-experience/utils.js
Labels: status: e2e tests passing

#212 Stop requesting to Reconnect to Square
  includes/Admin/Rest/WC_REST_Square_Settings_Controller.php
  src/new-user-experience/onboarding/data/reducers.js
  src/new-user-experience/settings/settings-app.js
  src/new-user-experience/utils.js
Labels: needs: UAT, status: e2e tests failing

#210 Avoid Confirmation Popup on Save Square Settings
  src/new-user-experience/settings/settings-app.js
Labels: needs: UAT, status: e2e tests failing

#207 Bump WooCommerce "tested up to" version 9.3
  woocommerce-square.php
Labels: needs: e2e testing, status: e2e tests passing

#221 Release/4.8.1
  changelog.txt
  includes/Admin/Rest/WC_REST_Square_Gift_Cards_Settings_Controller.php
  includes/Gateway/Gift_Card.php
  includes/Handlers/Products.php
  package-lock.json
  package.json
  readme.txt
  woocommerce-square.php
Labels: needs: e2e testing, needs: qit default tests, status: e2e tests passing

#225 Bump WooCommerce "tested up to" version 9.4
  readme.txt
  woocommerce-square.php
Labels: status: e2e tests passing
