Repository woocommerce/woocommerce-square, pull requests merged in 2024-08, with the labels that each got.

#152 Enhancement/E2E: Added some additional tests including tests related to subscriptions and pre-orders.
  .gitattributes
  .github/workflows/e2e.yml
  .gitignore
  .wp-env.json
  Gruntfile.js
  package.json
  tests/bin/install-plugins.sh
  tests/e2e/specs/a6.transaction-authorize.spec.js
  tests/e2e/specs/a7.transaction-authorize-virtual-only.spec.js
  tests/e2e/specs/a8.transaction-authorize-paid-order.spec.js
  tests/e2e/specs/a9.transaction-capture.spec.js
  tests/e2e/specs/a91.card-logos.spec.js
  tests/e2e/specs/a92.currency-support.spec.js
  tests/e2e/specs/a93.credit-card-form-fields.spec.js
  tests/e2e/specs/b1.tokenization.spec.js
  tests/e2e/specs/b4.gift-card-partial-payment.spec.js
  tests/e2e/specs/b7.gift-card-partial-payment-partial-refund.spec.js
  tests/e2e/specs/b8.gift-card-product.spec.js
  tests/e2e/specs/c1.gift-card-product-refund.spec.js
  tests/e2e/specs/c3.woo-sor.spec-with-inventory.spec.js
  tests/e2e/specs/e1.subscriptions.spec.js
  tests/e2e/specs/f1.pre-orders.spec.js
  tests/e2e/utils/helper.js
Labels: changelog: none, needs: e2e testing, status: e2e tests passing

#142 WooPayments Compatibility
  README.md
  includes/Gateway/Templates/payment.php
  includes/Plugin.php
  includes/WC_Payments_Compatibility.php
Labels: needs: e2e testing

#170 Ensure the "Uncaught TypeError" JavaScript console error does not occur for out-of-stock products.
  assets/js/frontend/wc-square-digital-wallet.js
Labels: needs: e2e testing

#178 Bump WooCommerce "tested up to" version 9.1
  tests/e2e/specs/c3.woo-sor.spec-with-inventory.spec.js
  woocommerce-square.php
Labels: needs: e2e testing

#195 Release/4.7.3
  changelog.txt
  includes/WC_Payments_Compatibility.php
  package-lock.json
  package.json
  readme.txt
  tests/e2e/specs/a1.plugin-activation.spec.js
  tests/e2e/specs/a4.gateway-status.spec.js
  tests/e2e/specs/d1.cash-app-pay.spec.js
  tests/e2e/utils/helper.js
  woocommerce-square.php
Labels: status: e2e tests passing

#200 fix/i18n: Add missing `i18n` directory
  package-lock.json
  package.json
Labels: status: e2e tests passing

#191 Update Product.php
  includes/Handlers/Product.php
Labels: needs: e2e testing

#201 Update Business Location Button Text Based on Location Count
  src/new-user-experience/onboarding/onboarding-app.js
Labels: needs: UAT, status: e2e tests passing

#183 fix/141: Add gift order item meta to cart when re-ordered.
  includes/Handlers/Order.php
Labels: status: e2e tests passing

#185 Fix potential infinite loop issue with pull_inventory step in Manual synchronization
  includes/Sync/Manual_Synchronization.php
Labels: needs: e2e testing, needs: UAT, status: e2e tests failing

#188 fix/143: Cancelling Google Pay on checkout shows validation errors
  src/blocks/credit-card/checkout-handler.js
  src/blocks/credit-card/use-payment-processing.js
  src/blocks/digital-wallets/content.js
  src/blocks/digital-wallets/hooks.js
  src/blocks/digital-wallets/utils.js
Labels: needs: e2e testing, status: e2e tests passing

#186 Replace the use of deprecated hook `wcs_renewal_order_meta` with `wc_subscriptions_renewal_order_data`
  includes/Framework/PaymentGateway/Integrations/Payment_Gateway_Integration_Subscriptions.php
Labels: needs: e2e testing, status: e2e tests failing

#72 feat/40: declare product compatibility
  .eslintrc.js
  includes/Admin/Product_Editor_Compatibility.php
  includes/Handlers/Products.php
  package-lock.json
  package.json
  src/admin/product-blocks/stock-management-field/block.json
  src/admin/product-blocks/stock-management-field/edit.js
  src/admin/product-blocks/stock-management-field/index.ts
  src/admin/product-blocks/stock-quantity-field/block.json
  src/admin/product-blocks/stock-quantity-field/edit.js
  src/admin/product-blocks/stock-quantity-field/index.ts
  src/admin/product-blocks/sync-with-square-field/block.json
  src/admin/product-blocks/sync-with-square-field/edit.tsx
  src/admin/product-blocks/sync-with-square-field/index.ts
  src/js/admin/wc-square-admin-products.js
  tests/e2e/config/env-post-setup.sh
  tests/e2e/specs/d6.woo-sor.spec-with-inventory-new-editor.spec.js
  tests/e2e/utils/helper.js
  woocommerce-square.php
Labels: status: blocked, needs: e2e testing, status: e2e tests failing
