Repository woocommerce/woocommerce-square, pull requests merged in 2024-11, with the labels that each got.

#230 Bump WordPress Tested up to version 6.7
  readme.txt
  woocommerce-square.php
Labels: needs: e2e testing, status: e2e tests passing, needs: WP RC test

#227 Ensure Square sync works without issues when using cached API response
  includes/Sync/Helper.php
  includes/Sync/Manual_Synchronization.php
Labels: status: e2e tests passing

#237 Remove woocommerce_loop_add_to_cart_link filter
  includes/Handlers/Products.php
Labels: status: e2e tests failing

#244 [E2E] Fix test c3.woo-sor.spec-with-inventory > OnePlus 8 pushed to Square with inventory
  tests/e2e/specs/c3.woo-sor.spec-with-inventory.spec.js
Labels: status: e2e tests failing
