Repository woocommerce/woocommerce-square, pull requests merged in 2025-05, with the labels that each got.

#343 Ensure that debug logs for payment gateways are being generated as expected.
  includes/Framework/PaymentGateway/Payment_Gateway.php
Labels: status: e2e tests passing

#323 Show detailed error messages on Checkout Page based on Debug Mode settings
  includes/Gateway.php
Labels: needs: UAT, status: e2e tests passing

#339 Add the onboarding URL to the "Complete setup" button on the new payment settings page.
  includes/Framework/PaymentGateway/Payment_Gateway.php
Labels: status: e2e tests passing

#329 Fix/318 Restore `update_from_square()` for Price Override Support
  includes/Handlers/Product.php
  includes/Sync/Interval_Polling.php
  includes/Sync/Manual_Synchronization.php
Labels: status: e2e tests passing

#350 [E2E] Update E2E tests to accommodate payment modernization changes in WooCommerce Core.
  tests/e2e/specs/a4.gateway-status.spec.js
  tests/e2e/specs/d1.cash-app-pay.spec.js
Labels: status: e2e tests passing

#352 Release/4.9.1
  changelog.txt
  includes/Framework/PaymentGateway/Payment_Gateway.php
  includes/Utilities/Performance_Logger.php
  package-lock.json
  package.json
  readme.txt
  tests/e2e/specs/d6.woo-sor.spec-with-inventory-new-editor.spec.js
  woocommerce-square.php
Labels: needs: qit e2e test, needs: qit api test, status: e2e tests passing

#354 Update gh-issue-gen.yml
  .github/workflows/gh-issue-gen.yml
Labels: changelog: none, status: e2e tests failing, status: e2e tests passing

#359 Release/4.9.2
  changelog.txt
  package-lock.json
  package.json
  readme.txt
  woocommerce-square.php
Labels: needs: qit default tests, status: e2e tests passing
