Repository woocommerce/woocommerce-square, pull requests merged in 2025-02, with the labels that each got.

#280 refresh WordPress.org assets
  wordpress-org-assets/banner-1544x500.png
  wordpress-org-assets/banner-772x250.png
  wordpress-org-assets/icon-128x128.png
  wordpress-org-assets/icon-160x160.png
  wordpress-org-assets/icon-256x256.png
Labels: status: e2e tests failing, status: e2e tests passing

#278 Bump WooCommerce "tested up to" version 9.7
  tests/e2e/specs/e1.subscriptions.spec.js
  tests/e2e/utils/helper.js
  woocommerce-square.php
Labels: needs: e2e testing, status: e2e tests passing

#284 Release/4.8.6
  changelog.txt
  includes/Handlers/Products.php
  package-lock.json
  package.json
  readme.txt
  woocommerce-square.php
Labels: status: e2e tests passing

#282 Ensure the correct UI is shown in the new WooCommerce payments settings.
  includes/Framework/PaymentGateway/Payment_Gateway.php
Labels: needs: UAT, status: e2e tests passing
