Repository woocommerce/woocommerce-square, pull requests merged in 2025-04, with the labels that each got.

#304 Fix deprecated PHP error in WooCommerce Square plugin
  includes/Framework/PaymentGateway/Payment_Gateway.php
Labels: needs: UAT, status: e2e tests passing

#308 Fix jQuery error on Cart & Checkout pages when subscription product is added
  src/blocks/digital-wallets/hooks.js
Labels: needs: UAT, status: e2e tests failing, status: e2e tests passing

#322 Compatibility testing with WordPress 6.8
  readme.txt
  woocommerce-square.php
Labels: needs: e2e testing, status: e2e tests failing, status: e2e tests passing, needs: WP RC test

#310 fix/292: Add support for WooCommerce's new Email Improvements feature added in 9.6
  includes/Emails/Gift_Card_Sent.php
  includes/Emails/WC_Square_Access_Token_Email.php
  includes/Emails/WC_Square_Gift_Card_Sent.php
  includes/Emails/WC_Square_Sync_Completed.php
  includes/Handlers/Email.php
  includes/Handlers/Product.php
  templates/emails/gift-card-sent.php
  templates/emails/plain/gift-card-sent.php
Labels: needs: UAT, status: e2e tests failing, status: e2e tests passing

#321 Remove Duplicate Onboarding Notice in WooCommerce Square
  includes/Plugin.php
Labels: needs: UAT, status: e2e tests failing, status: e2e tests passing

#326 Release/4.9.0
  changelog.txt
  includes/API.php
  includes/Emails/WC_Square_Gift_Card_Sent.php
  includes/Emails/WC_Square_Sync_Completed.php
  includes/Sync/Manual_Synchronization.php
  includes/Sync/Product_Import.php
  package-lock.json
  package.json
  readme.txt
  woocommerce-square.php
Labels: needs: qit default tests, status: e2e tests passing
