Repository woocommerce/woocommerce-square, pull requests merged in 2025-07, with the labels that each got.

#266 fix/261: Prevent "Sync with Square" from unchecking in Firefox
  src/js/admin/wc-square-admin-products.js
Labels: needs: UAT, status: e2e tests failing, status: e2e tests passing

#375 Release/4.9.6
  changelog.txt
  package-lock.json
  package.json
  readme.txt
  woocommerce-square.php
Labels: needs: qit default tests, status: e2e tests passing

#379 Fix the CARD_DECLINED_VERIFICATION_REQUIRED error for the credit card payment method.
  bin/docker-setup.sh
  includes/Framework/PaymentGateway/PaymentTokens/Payment_Gateway_Payment_Tokens_Handler.php
  includes/Framework/PaymentGateway/Payment_Gateway.php
  includes/Framework/PaymentGateway/Payment_Gateway_Direct.php
  includes/Gateway.php
  includes/Gateway/API/Requests/Card.php
  includes/Gateway/API/Requests/Payments.php
  includes/Gateway/API/Requests/Transactions.php
  includes/Gateway/Blocks_Handler.php
  includes/Gateway/Payment_Form.php
  src/blocks/credit-card/checkout-handler.js
  src/blocks/credit-card/use-payment-form.js
  src/blocks/credit-card/use-payment-processing.js
  src/blocks/square-utils/type-defs.js
  src/blocks/square-utils/utils.js
  src/js/frontend/wc-square.js
  tests/e2e/dummy-data/index.js
  tests/e2e/specs/a6.transaction-authorize.spec.js
  tests/e2e/specs/a7.transaction-authorize-virtual-only.spec.js
  tests/e2e/specs/a8.transaction-authorize-paid-order.spec.js
  tests/e2e/specs/a9.transaction-capture.spec.js
  tests/e2e/specs/b1.tokenization.spec.js
  tests/e2e/specs/b2.add-payment.method.spec.js
  tests/e2e/specs/e1.subscriptions.spec.js
  tests/e2e/specs/f1.pre-orders.spec.js
  tests/e2e/utils/helper.js
Labels: status: e2e tests passing

#383 Release/4.9.7
  changelog.txt
  includes/Gateway.php
  package-lock.json
  package.json
  readme.txt
  woocommerce-square.php
Labels: needs: qit default tests, status: e2e tests passing
