Repository woocommerce/woocommerce-square, pull requests merged in 2025-08, with the labels that each got.

#393 Ensure there is no fatal error on the product page when the product price is blank.
  includes/Gateway/Digital_Wallet.php
  tests/e2e/utils/helper.js
Labels: status: e2e tests passing

#385 Enhanced Option Assignment in Multiple Variations
  includes/Handlers/Product/Woo_SOR.php
Labels: status: e2e tests passing

#381 fix/SQUARE-139: Fix the production and sandbox connection flow
  src/new-user-experience/settings/settings-app.js
Labels: status: e2e tests failing, status: e2e tests passing

#391 Remove loading translations, as it is automatically handled by WordPress since version 4.6.
  includes/Framework/Plugin.php
Labels: status: e2e tests failing, status: e2e tests passing

#224 fix/202: make "You're connected to Square" page entire UI to be visible
  src/new-user-experience/components/onboarding-header/index.js
  src/new-user-experience/components/onboarding-header/index.scss
  src/new-user-experience/onboarding/onboarding-app.js
  src/new-user-experience/onboarding/steps/payment-complete/index.js
  src/new-user-experience/onboarding/steps/payment-methods/index.js
  src/new-user-experience/styles/index.scss
  src/new-user-experience/styles/onboarding.scss
Labels: needs: UAT, status: e2e tests failing, status: e2e tests passing

#396 Add Opt-in setting for bidirectional order sync
  .github/workflows/e2e.yml
  includes/Admin/Rest/WC_REST_Square_Settings_Controller.php
  includes/Gateway.php
  includes/Gateway/API.php
  includes/Gateway/API/Requests/Orders.php
  includes/Gateway/API/Responses/Search_Orders.php
  includes/Gateway/Cash_App_Pay_Gateway.php
  includes/Handlers/Order_Sync.php
  includes/Plugin.php
  includes/Settings.php
  includes/Sync/Order_Importer.php
  includes/Sync/Order_Mapper.php
  includes/Sync/Order_Polling.php
  src/new-user-experience/modules/configure-sync/index.js
  src/new-user-experience/onboarding/data/reducers.js
  src/new-user-experience/utils.js
  tests/e2e/specs/d9.order-sync-fulfillment.spec.js
  woocommerce-square.php
Labels: status: e2e tests passing

#398 Ensure sync isn’t interrupted in case of a category insert failure.
  includes/Handlers/Category.php
Labels: status: e2e tests passing
