Repository woocommerce/woocommerce-square, pull requests merged in 2025-06, with the labels that each got.

#342 Add Support for EMV 3-D Secure to Comply with Japan METI Regulation
  includes/Gateway/API/Requests/Card.php
  includes/Gateway/API/Requests/Payments.php
  includes/Gateway/API/Requests/Transactions.php
  src/blocks/credit-card/use-payment-form.js
  src/blocks/credit-card/use-payment-processing.js
  src/blocks/square-utils/type-defs.js
  src/js/frontend/wc-square.js
Labels: status: e2e tests failing, status: e2e tests passing

#348 Indicate customer initiated payments.
  includes/Gateway/API/Requests/Payments.php
Labels: status: e2e tests failing, status: e2e tests passing

#358 Fix: Only sync attributes "Used for Variations" to Square
  includes/Handlers/Product/Woo_SOR.php
Labels: status: e2e tests passing

#340 Upgrade Square PHP SDK to v40
  composer.json
  composer.lock
Labels: status: e2e tests passing

#363 Release/4.9.3
  changelog.txt
  includes/Gateway.php
  includes/Handlers/Product/Woo_SOR.php
  package-lock.json
  package.json
  readme.txt
  woocommerce-square.php
Labels: needs: qit default tests, status: e2e tests passing

#367 Ensure there is no fatal error at checkout when using a $0 local pickup shipping method.
  includes/Gateway/API/Requests/Orders.php
Labels: needs: e2e testing, status: e2e tests passing

#370 Compatibility testing with WC 10.0
  woocommerce-square.php
Labels: needs: e2e testing, status: e2e tests passing

#366 Ensure the customer is created on the Square side without errors when adding a payment method.
  includes/Framework/PaymentGateway/Payment_Gateway_Direct.php
Labels: status: e2e tests passing

#360 Fix E2E
  tests/e2e/specs/c4.product-import.spec.js
Labels: changelog: none, status: e2e tests passing
