Repository woocommerce/woocommerce-square, pull requests merged in 2025-03, with the labels that each got.

#290 Ensure that Cash App Pay works as expected on mobile device.
  src/blocks/cash-app-pay/utils.js
Labels: needs: UAT, status: e2e tests passing

#294 Ensure that no blank order is created via the "Add Payment Method" when HPOS is enabled.
  includes/Gateway.php
Labels: status: e2e tests passing

#293 Disable Warnings from WordPress Plugin Check Action
  .github/workflows/plugin-check.yml
Labels: status: e2e tests passing

#277 Add support for syncing the "Mark as Sold Out" field value during inventory sync.
  includes/Handlers/Product.php
  includes/Handlers/Product/Woo_SOR.php
  includes/Sync/Helper.php
  includes/Sync/Interval_Polling.php
  includes/Sync/Manual_Synchronization.php
  includes/Sync/Product_Import.php
  src/js/admin/wc-square-admin-products.js
Labels: status: e2e tests passing

#287 Release/4.8.7
  changelog.txt
  includes/Framework/PaymentGateway/Payment_Gateway.php
  package-lock.json
  package.json
  readme.txt
  woocommerce-square.php
Labels: status: e2e tests failing, status: e2e tests passing

#305 Improve E2E test setup
  .github/workflows/e2e.yml
  .wp-env.json
Labels: status: e2e tests failing, status: e2e tests passing

#313 Update all actions we use in our workflows to pull from specific pinned commits
  .github/workflows/backlog-automation-issues.yml
  .github/workflows/e2e.yml
  .github/workflows/eslint.yml
  .github/workflows/generate-zip.yml
  .github/workflows/php-compat.yml
  .github/workflows/phpcs.yml
  .github/workflows/plugin-check.yml
  .github/workflows/qit.yml
  .github/workflows/release.yml
Labels: needs: qit default tests, status: e2e tests failing, status: e2e tests passing

#298 Bump WooCommerce "tested up to" version 9.8
  woocommerce-square.php
Labels: needs: e2e testing, status: e2e tests failing, status: e2e tests passing

#314 Fix E2E tests for remove label errors
  .github/workflows/e2e.yml
Labels: needs: e2e testing, status: e2e tests failing, status: e2e tests passing
